import os
import pandas as pd
import numpy as np

results_folder = r"C:\adas-thesis\results\raw_scripted"
output_summary = r"C:\adas-thesis\results\thesis_summary_scripted.csv"

# Find all the CSV files our runner generated
files = [f for f in os.listdir(results_folder) if f.endswith('.csv') and not f.startswith('test')]
summary_data = []

print("Analyzing simulation data...\n")

for f in files:
    filepath = os.path.join(results_folder, f)
    
    try:
        # Read the raw CSV generated by esmini
        df = pd.read_csv(filepath)
        
        # CRITICAL FIX 1: Strip invisible spaces from the column headers
        df.columns = df.columns.str.strip()
        
        # CRITICAL FIX 2: Strip invisible spaces from the vehicle names
        if 'name' in df.columns:
            df['name'] = df['name'].astype(str).str.strip()
        else:
            print(f"Skipping {f}: No 'name' column found even after stripping spaces.")
            continue
            
        # Isolate the Ego and Obstacle rows into their own DataFrames
        df_ego = df[df['name'] == 'Ego'].copy()
        df_obs = df[df['name'] == 'Obstacle'].copy()
        
        # Rename columns to keep them straight when we combine them
        df_ego = df_ego[['time', 'x', 'y', 'speed']].rename(columns={'x': 'x_ego', 'y': 'y_ego', 'speed': 'speed_ego'})
        df_obs = df_obs[['time', 'x', 'y']].rename(columns={'x': 'x_obs', 'y': 'y_obs'})
        
        # Match up the Ego and Obstacle data row-by-row based on the simulation 'time'
        merged = pd.merge(df_ego, df_obs, on='time')
        
        # Calculate the physical distance between the two cars at every single frame
        merged['Distance'] = np.sqrt((merged['x_ego'] - merged['x_obs'])**2 + (merged['y_ego'] - merged['y_obs'])**2)
        
        # Find the absolute closest they ever got to each other
        min_distance = merged['Distance'].min()
        
        # A standard car is about 4.5 meters long. If distance is less than that, they collided.
        collision_flag = 1 if min_distance <= 4.5 else 0
        
        # Find the exact moment in time where the distance was the smallest
        impact_row = merged.loc[merged['Distance'].idxmin()]
        
        # Grab the speed at that exact moment (0 if they didn't crash)
        impact_speed_ms = impact_row['speed_ego'] if collision_flag == 1 else 0.0
        impact_speed_kph = impact_speed_ms * 3.6
        
        # Add the results to our final table
        summary_data.append({
            'Scenario': f.replace('.csv', ''),
            'Collision': collision_flag,
            'Min_Distance_m': round(min_distance, 2),
            'Impact_Speed_kph': round(impact_speed_kph, 1)
        })
        
    except Exception as e:
        print(f"Error reading {f}: {e}")

# Save the final neat table for your thesis
if summary_data:
    summary_df = pd.DataFrame(summary_data)
    # Sort alphabetically so speeds and friction levels are grouped nicely
    summary_df = summary_df.sort_values(by='Scenario')
    summary_df.to_csv(output_summary, index=False)
    
    print(f"Summary table created successfully at: {output_summary}\n")
    print(summary_df.to_string(index=False))
else:
    print("No valid CSV data found to analyze.")